#!/usr/bin/lua
local site = require 'gluon.site'
local util = require 'gluon.util'
local uci = require('simple-uci').cursor()

uci:delete('wireguard', 'mesh_vpn', 'user')

local add_groups

local function generate_wg_iface_name(peer)
  return "mesh_wg_" .. peer
end

local function add_peer(group, name, config)
  uci:section('network', 'interface', generate_wg_iface_name(name) .. 'm', {
    type = 'wireguard',
    ifname = generate_wg_iface_name(name),
    proto = 'gluon_mesh',
  })

  uci:section('network', 'interface', generate_wg_iface_name(name) .. 's', {
    ip6addr = 'fe80::2/64',
    ifname = generate_wg_iface_name(name),
    proto = 'static',
  })

  uci:section('network', 'interface', generate_wg_iface_name(name) .. 'w', {
    ifname = generate_wg_iface_name(name),
    proto = 'gluon_wireguard',
  })

  uci:section('wireguard', 'peer', group .. '_peer_' .. name, {
    enabled = true,
    net = 'mesh_vpn',
    ifname = generate_wg_iface_name(name),
    group = group,
    key = config.key,
    remote = config.remote,
    allowedIPs = '::/0',
  })
end

local function add_group(name, config, parent)
  uci:delete('wireguard', name)
  uci:delete_all('wireguard', 'peer', function(peer)
    return (peer.net == 'mesh_vpn' and peer.group == name)
  end)


  uci:section('wireguard', 'peer_group', name, {
    enabled = true,
    net = 'mesh_vpn',
    parent = parent,
    peer_limit = config.limit,
  })

  if config.peers then
    for peername, peerconfig in pairs(config.peers) do
      add_peer(name, peername, peerconfig)
    end
  end

  add_groups(name, config.groups, name)
end

-- declared local above
function add_groups(prefix, groups, parent)
  if groups then
    for name, group in pairs(groups) do
      add_group(prefix .. '_' .. name, group, parent)
    end
  end
end

add_groups('mesh_vpn', site.mesh_vpn.wireguard.groups())

if site.mesh_vpn.wireguard.groups.backbone.enabled(true) then
uci:section('wireguard', 'wireguard', 'mesh_vpn', {
	enabled = true,
	group = 'mesh_vpn_backbone',
	mtu = site.mesh_vpn.mtu(),
	secret = '/lib/gluon/mesh-vpn/wireguard',
	packet_mark = 1,
})
end

uci:save('network')
uci:save('wireguard')
